spring:
  application:
    name: chat-app

  datasource:
    url: jdbc:postgresql://localhost:5432/chat-db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: "fGh9Jr4qX8i1Bv0nW3sR2kL5yT7pMv7z"
